# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: db40a5f8d648ddcea0c0d7e52e7f42e39aec3171f49feb86a708948202d23f57912bdde436a1517ff3ef83cb8d22b6dab3177635a50267607f520d833774d8cb

test:
  secret_key_base: 71eaff7dfb7c96e078d49a6abc24cf3191950cb2dda0122d35dfcaad5429b56095d1d7dedc681ba5577a0cacb2e18224b651096060303ba9e8a3345691ad8505

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
